name: Trigger all release processes

on:
  repository_dispatch:
    types:
      - new_release
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.prepare.outputs.tag }}
    steps:
      - id: prepare
        name: Pass the right tag depending on the event
        run: |
          event=${{ github.event_name }}
          if [[ $event == "workflow_dispatch" ]]; then
            tag=$(curl -s https://releases.rocket.chat/stable/info | jq .tag -r)
          else
            tag=${{ github.event.client_payload.tag }}
          fi
          echo "tag: $tag"
          # for now we skip all release candidates
          grep -Eq 'rc$' <<<"$tag" && exit 1
          [[ -n "$tag" ]] && echo "tag=$tag" >>$GITHUB_OUTPUT # else intentional fail

  snap-run:
    needs:
      - prepare
    uses: "RocketChat/rocketchat-server-snap/.github/workflows/build_and_release.yml@develop"
    with:
      tag: ${{ needs.prepare.outputs.tag }}
    secrets:
      snapcraft-credential: ${{ secrets.SNAPCRAFT_CREDENTIAL }}
      github-token: ${{ secrets.GH_PERSONAL_TOKEN }}

  packer-run:
    needs:
      - prepare
    uses: "RocketChat/rocketchat-packer/.github/workflows/build_images.yml@main"
    with:
      tag: ${{ needs.prepare.outputs.tag }}
    secrets:
      aws-key-id: ${{ secrets.AWS_KEY_ID }}
      aws-secret-key: ${{ secrets.AWS_SECRET_KEY }}
      digitalocean-token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      github-token: ${{ secrets.GH_PERSONAL_TOKEN }}
  
  helm-run:
    needs:
      - prepare
    uses: "RocketChat/helm-charts/.github/workflows/release-helm.yml@master"
    with:
      tag: ${{ needs.prepare.outputs.tag }}
    secrets:
      github-token: ${{ secrets.GH_PERSONAL_TOKEN }}
